package abd.p1.view;

import abd.p1.controller.loginController;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

/**
 * Clase que muestra una ventana para poder realizar el login en la aplicación
 * o para poder registrarse en la misma.
 *
 * @author Alejandro Huertas Herrero 3ºB.
 */
@SuppressWarnings("serial")
public class Login extends javax.swing.JDialog
{
    private final loginController controller;

    public Login(java.awt.Frame parent, boolean modal, loginController controller)
    {
        super(parent, modal);
        
        initComponents();

        this.controller = controller;
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tittleLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        passTextField = new javax.swing.JPasswordField();
        capsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvenido!");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setResizable(false);

        tittleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titulo.png"))); // NOI18N

        emailLabel.setDisplayedMnemonic('D');
        emailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        emailLabel.setText("Dirección de correo:");

        passLabel.setDisplayedMnemonic('C');
        passLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        passLabel.setText("Contraseña:");

        emailTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        acceptButton.setBackground(new java.awt.Color(0, 255, 84));
        acceptButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(0, 0, 0));
        acceptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AcceptIcon.png"))); // NOI18N
        acceptButton.setMnemonic('A');
        acceptButton.setText("Aceptar");
        acceptButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acceptButtonActionPerformed(evt);
            }
        });

        newUserButton.setBackground(new java.awt.Color(0, 158, 255));
        newUserButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        newUserButton.setForeground(new java.awt.Color(0, 0, 0));
        newUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewUserIcon.png"))); // NOI18N
        newUserButton.setMnemonic('N');
        newUserButton.setText("Nuevo usuario");
        newUserButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newUserButtonActionPerformed(evt);
            }
        });

        passTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        passTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                passTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                passTextFieldFocusLost(evt);
            }
        });
        passTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                passTextFieldKeyPressed(evt);
            }
        });

        capsLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addComponent(passLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTextField)
                    .addComponent(passTextField)
                    .addComponent(capsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(acceptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newUserButton)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passLabel)
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(capsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(newUserButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
	private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed

        String email = emailTextField.getText(), pass = passTextField.getText();

        if (email.equals("") || pass.equals(""))
            JOptionPane.showMessageDialog(null, "Debes introducir usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/ErrorIcon.png")));
        else
        {
            try
            {
                controller.chekUser(email, pass);
                setVisible(false);
            }
            catch (Exception error)
            {
                JOptionPane.showMessageDialog(null, error.getMessage(), "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/ErrorIcon.png")));
            }
        }

        passTextField.setText("");
    }//GEN-LAST:event_acceptButtonActionPerformed

    @SuppressWarnings("deprecation")
	private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed

        String email = emailTextField.getText(), pass = passTextField.getText(), 
               com = email.substring(email.length() - 4, email.length()), es = email.substring(email.length() - 3, email.length());

        if (email.equals("") || pass.equals(""))
            JOptionPane.showMessageDialog(null, "Debes introducir usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/ErrorIcon.png")));
        
        else if ((!email.contains("@") || !com.equals(".com")) && (!email.contains("@") || !es.equals(".es")))
            JOptionPane.showMessageDialog(null, "Debes introducir un correo válido.", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/ErrorIcon.png")));
        
        else
        {
            if(!controller.isAlredyInDataBase(email))
            {
                this.controller.newUser(email, pass, this);

                if (this.controller.getConectedUser()!= null)
                    setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(null, "Usuario ya registrado, inicia sesión.", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/ErrorIcon.png")));
        }
        
        passTextField.setText("");
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void passTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextFieldKeyPressed
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK))
            this.capsLabel.setText("TECLA DE MAYÚSCULAS ACTIVADA");
        else
            this.capsLabel.setText("");
    }//GEN-LAST:event_passTextFieldKeyPressed

    private void passTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_passTextFieldFocusGained
    {//GEN-HEADEREND:event_passTextFieldFocusGained
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK))
            this.capsLabel.setText("TECLA DE MAYÚSCULAS ACTIVADA");
        else
            this.capsLabel.setText("");
    }//GEN-LAST:event_passTextFieldFocusGained

    private void passTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_passTextFieldFocusLost
    {//GEN-HEADEREND:event_passTextFieldFocusLost
        this.capsLabel.setText("");
    }//GEN-LAST:event_passTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel capsLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton newUserButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}