package abd.p1.view;

import abd.p1.view.observers.profileObserver;
import abd.p1.controller.profileController;
import abd.p1.model.Mensaje;
import abd.p1.model.Usuario;

import java.text.DecimalFormat;

import java.util.List;
import java.util.Set;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 * Clase que muestra una ventana para ver el perfil de un usuario.
 *
 * @author Alejandro Huertas Herrero 3ºB.
 */
@SuppressWarnings("serial")
public class Profile extends javax.swing.JDialog implements profileObserver
{
    private profileController controller;
    private DefaultListModel<String> hobbies;
    private DefaultListModel<String> equalsHobbies;
    private HTMLEditorKit kit;
    private HTMLDocument doc;

    public Profile(javax.swing.JDialog parent, boolean modal, profileController controller)
    {
        super(parent, modal);
        
        hobbies = new DefaultListModel<>();
        equalsHobbies = new DefaultListModel<>();
        kit = new HTMLEditorKit();
        doc = new HTMLDocument();
        
        initComponents();
        
        this.controller = controller;
        this.controller.setObserver(this);
        this.controller.getUser();
        this.controller.getDistance();
        this.controller.getCompatibility();
        this.controller.getEqualsHobbies();
        this.controller.areFriends();
        this.controller.getAllChat();
        
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hobbiesList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        gendreLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        preferenceLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionPane = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        compatibilityLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        equalsHobbiesList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        chatPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        sendRequestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de perfil");
        setResizable(false);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameLabel.setText("Name");

        ageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(0, 0, 0));
        ageLabel.setText("Age");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Aficiones:");

        jScrollPane2.setFocusable(false);

        hobbiesList.setBackground(new java.awt.Color(255, 255, 255));
        hobbiesList.setModel(hobbies
        );
        hobbiesList.setFocusable(false);
        hobbiesList.setRequestFocusEnabled(false);
        hobbiesList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                hobbiesListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hobbiesList);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sexo:");

        gendreLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        gendreLabel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Busca:");

        preferenceLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        preferenceLabel.setForeground(new java.awt.Color(0, 0, 0));

        descriptionPane.setEditable(false);
        descriptionPane.setFocusable(false);
        jScrollPane4.setViewportView(descriptionPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gendreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preferenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageLabel))
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gendreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(preferenceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Perfil", jPanel1);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tu nivel de compatibilidad es de:");

        compatibilityLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        compatibilityLabel.setForeground(new java.awt.Color(0, 0, 0));
        compatibilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Intereses comunes:");

        equalsHobbiesList.setBackground(new java.awt.Color(255, 255, 255));
        equalsHobbiesList.setModel(equalsHobbies);
        jScrollPane3.setViewportView(equalsHobbiesList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compatibilityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compatibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compatibilidad", jPanel2);

        jLabel3.setDisplayedMnemonic('E');
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enviar mensaje:");

        messageTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        messageTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                messageTextFieldActionPerformed(evt);
            }
        });

        chatPane.setEditable(false);
        chatPane.setContentType("<html>");
        chatPane.setDocument(doc);
        chatPane.setEditorKit(kit
        );
        jScrollPane5.setViewportView(chatPane);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chat", jPanel3);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Distancia:");

        sendRequestButton.setBackground(new java.awt.Color(0, 255, 151));
        sendRequestButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sendRequestButton.setForeground(new java.awt.Color(0, 0, 0));
        sendRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddFriendIcon.png"))); // NOI18N
        sendRequestButton.setMnemonic('E');
        sendRequestButton.setText("Enviar petición de amistad");
        sendRequestButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sendRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendRequestButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(distanceLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendRequestButton)
                        .addContainerGap())))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Perfil");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sendRequestButtonActionPerformed
    {//GEN-HEADEREND:event_sendRequestButtonActionPerformed
        controller.addFriend();
        sendRequestButton.setEnabled(false);
    }//GEN-LAST:event_sendRequestButtonActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_messageTextFieldActionPerformed
    {//GEN-HEADEREND:event_messageTextFieldActionPerformed
        if(!messageTextField.getText().equals(""))
            controller.sendMessage(messageTextField.getText());
        
        messageTextField.setText("");
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void hobbiesListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hobbiesListMouseClicked
    {//GEN-HEADEREND:event_hobbiesListMouseClicked
        hobbiesList.clearSelection();
    }//GEN-LAST:event_hobbiesListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextPane chatPane;
    private javax.swing.JLabel compatibilityLabel;
    private javax.swing.JTextPane descriptionPane;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JList<String> equalsHobbiesList;
    private javax.swing.JLabel gendreLabel;
    private javax.swing.JList<String> hobbiesList;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel preferenceLabel;
    private javax.swing.JButton sendRequestButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void seeUser(Usuario user)
    {
        iconLabel.setIcon(new ImageIcon(user.getAvatar()));

        nameLabel.setText(user.getNombre());

        if (user.getFecha_nacimiento() != null)
            ageLabel.setText(String.valueOf(user.calculateAge(user.getFecha_nacimiento())) + " años.");

        gendreLabel.setText(user.getGenero().toString());
        preferenceLabel.setText(user.getGenero_interes().toString());
        descriptionPane.setText(user.getDescripcion());
        controller.getHobbies();
    }

    @Override
    public void showDistance(double distance)
    {
        distanceLabel.setText(new DecimalFormat("##.##").format(distance) + " m.");
    }

    @Override
    public void showUserHobbies(Set<String> hobbies)
    {
        this.hobbies.clear();
        hobbiesList.removeAll();

        for (String s : hobbies)
            this.hobbies.addElement(s);

        hobbiesList.clearSelection();
    }

    @Override
    public void showCompatibility(double compatibility)
    {
        compatibilityLabel.setText(String.valueOf(new DecimalFormat("##").format(compatibility)) + " %");
    }

    @Override
    public void showEqualsHobbies(Set<String> hobbies)
    {
        equalsHobbies.clear();
        equalsHobbiesList.removeAll();

        for (String s : hobbies)
            equalsHobbies.addElement(s);

        equalsHobbiesList.clearSelection();
    }

    @Override
    public void activeButton(boolean active)
    {
        if (active)
            sendRequestButton.setEnabled(true);
        else
            sendRequestButton.setEnabled(false);
    }

    @Override
    public void showMessage(Mensaje message)
    {
        StringBuilder buffer = new StringBuilder();
        
        if(chatPane.getText().contains("["))
        {
            buffer.append(chatPane.getText().replace("</body>\n</html>", ""));
            buffer.append(message.getFormatText());
            buffer.append("</boyd>\n</html>");
        }
        else
            buffer.append(message.getFormatText());
        
        chatPane.setText(buffer.toString());
    }

    @Override
    public void showMessages(List<Mensaje> messages)
    {
        StringBuilder buffer = new StringBuilder();

        for (Mensaje m : messages)
            buffer.append(m.getFormatText());

        chatPane.setText(buffer.toString());
    }
}